version: 2.1

jobs:
    build:
        machine: true
        steps:
             - checkout
             - run:
                 - name: Gradle build
                 - command: |
                      export TERM=hi
                      gradle build 
